#!/usr/bin/env python3
"""E0b — does the UNet's spacing conditioning actually change what gets drawn?

Same case, same report, same noise seed; only the spacing fed to the UNet varies. Two
readings tell the whole story, both in ORIGINAL GRID VOXELS (the model's own units, so the
declared spacing cannot leak in):

    rel-L2 vs the 0.8 reference   0  => the conditioning is ignored outright
    body A-P extent vs s          flat        => content is spacing-blind (hypothesis A only)
                                  ∝ 1/s       => the model fully rescales anatomy (hypothesis B)
                                  in between  => partial compensation, and the slope says how much

The 0.8 and 1.0 points are reused from the main arms (identical seed and code path); only the
extra spacings are generated here.

Raw saved volumes are indexed (Z, Y, X) = (S, A, R): report2ct encodes after
`Orientationd(RAS)` and saves H=R, W=A, D=S, so axis 1 is anterior-posterior.

Usage:
    CUDA_VISIBLE_DEVICES=2 python tests/spacing_fov/content_invariance.py --generate
    python tests/spacing_fov/content_invariance.py            # analyse only
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import SimpleITK as sitk  # noqa: E402

sys.path.insert(0, "/workspace")

from tests.spacing_fov._common import bbox_extent, body_mask  # noqa: E402

HERE = pathlib.Path(__file__).parent
FIGS = HERE / "figs"
RESULTS = HERE / "results"
PROBE = HERE / "_invariance"

Z_MM = 1.5
REFERENCE = 0.8
# 0.8 / 1.0 reuse the main arms; the rest are generated by this script. 3.0 mm is the top of
# the MAISI spacing-conditioning range and is included as a deliberate stress point.
EXTRA_SPACINGS = [0.7, 1.5, 3.0]
ARM_DIRS = {0.8: HERE / "preds" / "gen_sp0.8", 1.0: HERE / "preds" / "gen_sp1.0"}


def _dir_for(s: float) -> pathlib.Path:
    return ARM_DIRS.get(s, PROBE / f"sp{s}")


def _pick_cases(n: int) -> list[str]:
    """First n cases present in both main arms (so 0.8 and 1.0 are always available)."""
    common = None
    for d in ARM_DIRS.values():
        ids = {p.stem for p in d.glob("*.mha")}
        common = ids if common is None else (common & ids)
    return sorted(common or [])[:n]


def _generate(cases: list[str], spacings: list[float]) -> None:
    """Generate the extra spacing points for exactly the chosen cases.

    The cases are passed explicitly via ``--cases``. Shrinking ``--n`` instead would be wrong:
    ``load_eval_cases`` picks its subset by a seeded shuffle over all 1304 scans and only then
    returns rows in DataFrame order, so a smaller ``--n`` is a DIFFERENT set of patients, not a
    prefix — the probe would have ended up comparing spacings across different people.
    """
    for s in spacings:
        out = _dir_for(s)
        print(f"[E0b] generating spacing {s} for {len(cases)} cases -> {out}")
        subprocess.run(
            [
                sys.executable,
                str(HERE / "gen_seeded.py"),
                "--spacing",
                str(s),
                str(s),
                str(Z_MM),
                "--n",
                "100",
                "--cases",
                *cases,
                "--out-dir",
                str(out),
            ],
            check=True,
        )


def _measure(path: pathlib.Path) -> dict:
    """Body extents (grid voxels) of one raw generated volume, array order (S, A, R)."""
    arr = sitk.GetArrayFromImage(sitk.ReadImage(str(path))).astype(np.float32)
    mask = body_mask(arr[::2, ::2, ::2])
    (si, ap, lr), _ = bbox_extent(mask)
    return {"body_ap_grid": ap * 2, "body_lr_grid": lr * 2, "body_si_grid": si * 2}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--cases", type=int, default=5)
    args = ap.parse_args()

    FIGS.mkdir(parents=True, exist_ok=True)
    RESULTS.mkdir(parents=True, exist_ok=True)

    cases = _pick_cases(args.cases)
    if not cases:
        sys.exit("main arms have no shared cases yet")
    print(f"[E0b] cases: {cases}")

    if args.generate:
        _generate(cases, EXTRA_SPACINGS)

    # Only keep spacings that cover EVERY case. A spacing missing some cases would otherwise be
    # averaged over a different set of patients from its neighbours, and the "does the model
    # rescale anatomy?" slope would be inter-patient variance wearing a conditioning costume.
    spacings = []
    for s in sorted([*ARM_DIRS, *EXTRA_SPACINGS]):
        missing = [c for c in cases if not (_dir_for(s) / f"{c}.mha").is_file()]
        if missing:
            print(
                f"[E0b] SKIPPING spacing {s}: missing {len(missing)}/{len(cases)} cases"
            )
            continue
        spacings.append(s)
    if REFERENCE not in spacings:
        sys.exit(
            f"reference spacing {REFERENCE} is incomplete — nothing to compare against"
        )
    print(f"[E0b] complete spacings: {spacings}")

    rows = []
    for case in cases:
        ref_path = _dir_for(REFERENCE) / f"{case}.mha"
        ref = sitk.GetArrayFromImage(sitk.ReadImage(str(ref_path))).astype(np.float32)
        ref_norm = float(np.linalg.norm(ref))
        for s in spacings:
            path = _dir_for(s) / f"{case}.mha"
            if not path.is_file():
                continue
            arr = sitk.GetArrayFromImage(sitk.ReadImage(str(path))).astype(np.float32)
            row = {
                "case": case,
                "spacing": s,
                "rel_l2_vs_0.8": float(np.linalg.norm(arr - ref) / ref_norm),
                **_measure(path),
            }
            rows.append(row)
            print(
                f"  {case:16s} s={s:<5} relL2={row['rel_l2_vs_0.8']:.4f} "
                f"body_ap_grid={row['body_ap_grid']}"
            )

    summary = {}
    for s in spacings:
        vals = [r for r in rows if r["spacing"] == s]
        if not vals:
            continue
        summary[str(s)] = {
            "n": len(vals),
            "rel_l2_mean": float(np.mean([r["rel_l2_vs_0.8"] for r in vals])),
            "body_ap_grid_mean": float(np.mean([r["body_ap_grid"] for r in vals])),
            "body_ap_grid_sd": float(np.std([r["body_ap_grid"] for r in vals])),
        }
    (RESULTS / "content_invariance.json").write_text(
        json.dumps({"summary": summary, "rows": rows}, indent=2)
    )

    # ---- figure ----
    xs = [float(k) for k in summary]
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
    axes[0].plot(xs, [summary[str(x)]["rel_l2_mean"] for x in xs], "o-")
    axes[0].set_xlabel("conditioned spacing (mm)")
    axes[0].set_ylabel(f"rel-L2 vs s={REFERENCE}")
    axes[0].set_title("content change vs conditioning (same seed)")
    axes[0].grid(alpha=0.3)

    means = np.array([summary[str(x)]["body_ap_grid_mean"] for x in xs])
    sds = np.array([summary[str(x)]["body_ap_grid_sd"] for x in xs])
    axes[1].errorbar(xs, means, yerr=sds, fmt="o-", capsize=3, label="measured")
    ref_mean = summary[str(REFERENCE)]["body_ap_grid_mean"]
    axes[1].plot(
        xs, [ref_mean] * len(xs), "--", color="0.6", label="spacing-blind (flat)"
    )
    axes[1].plot(
        xs,
        [ref_mean * REFERENCE / x for x in xs],
        ":",
        color="tab:red",
        label="fully spacing-faithful (1/s)",
    )
    axes[1].set_xlabel("conditioned spacing (mm)")
    axes[1].set_ylabel("body A-P extent (original grid voxels)")
    axes[1].set_title("does the model rescale anatomy?")
    axes[1].legend(fontsize=8)
    axes[1].grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(FIGS / "F6_content_invariance.png", dpi=150)
    plt.close(fig)
    print(
        f"\n[E0b] → {RESULTS / 'content_invariance.json'}, {FIGS / 'F6_content_invariance.png'}"
    )


if __name__ == "__main__":
    main()
